sonar.projectKey=catch-oss_ss-twig-elemental
sonar.organization=catch-design
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.php.coverage.reportPaths=coverage/php/coverage.xml
sonar.php.tests.reportPath=coverage/php/junit.xml
sonar.exclusions=vendor/**,tests/**
